files:
  - source: /doc/src/*/*.md
    translation: /l10n/%locale_with_underscore%/%original_path%/%original_file_name%
  - source: /stdlib/*/docs/src/index.md
    translation: /l10n/%locale_with_underscore%/%original_path%/%original_file_name%
